# Generated by Django 2.1.2 on 2018-10-11 10:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_db_constraints.operations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert_history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('message', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('0', 'success'), ('1', 'info'), ('2', 'warning'), ('3', 'error')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.SlugField(max_length=12)),
                ('ip', models.GenericIPAddressField(default='0.0.0.0', protocol='IPv4')),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Camera_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_model', models.CharField(max_length=100)),
                ('custom_camera_url', models.CharField(help_text='Use {admin} and {password} for creditentials, and {ip} for adress of the webcam', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('value', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1.0)])),
                ('max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='camera_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_types', to='rest.Camera_type'),
        ),
        django_db_constraints.operations.AlterConstraints(
            name='Infrastructure',
            db_constraints={'value_range': 'check (value >=0.0 AND value <=1.0 )'},
        ),
    ]
