# Generated by Django 2.1.2 on 2018-10-11 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.SlugField(max_length=35)),
                ('origin_camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_zones', to='rest.Camera')),
            ],
        ),
        migrations.CreateModel(
            name='ZonePolygon',
            fields=[
                ('point_no', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygons', to='rest.Zone')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='zonepolygon',
            unique_together={('x', 'y', 'zone')},
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('name', 'origin_camera')},
        ),
    ]
